
version: '3'

services:
  sql-server-db-omg:
    container_name: sql-server-db-omg
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Pass@word
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
